### ISSUE TITLE
script/install Invalid or missing Program/ProgramArguments

### ISSUE THREAD

**Issue by luxus** [maddox/itunes-api#11]
```
:itunes-api kai$ script/install
Installing itunes-api...
/Users/kai/Library/LaunchAgents/org.itunes-api.plist: Invalid or missing Program/ProgramArguments
```
thats happens when i try to install the script..
it is working fine with script/server

**Comment by luxus** [comment]
kai$ launchctl load -w -F ~/Library/LaunchAgents/org.itunes-api.plist
/Users/kai/Library/LaunchAgents/org.itunes-api.plist: Invalid or missing Program/ProgramArguments

**Comment by maddox** [comment]
fixed in 5d95cbecfcb81649d7dda47c72ec71f9dcea51da

**Comment by luxus** [comment]
still the same error .. the file "~/Library/LaunchAgents/org.itunes-api.plist" exists

**Comment by maddox** [comment]
Could you paste the content of the plist in here?

**Comment by kfgoode** [comment]
Hi, I am actually having the same issue, I have set permissions using CHMOD but getting the same error 

Installing itunes-api...
/Users/kfgoode/Library/LaunchAgents/org.itunes-api.plist: Invalid or missing Program/ProgramArguments

I do see the plist file in both config and in the launch agents directory.

Any help would be appreciated.

**Comment by maddox** [comment]
This was fixed with 695fec3ebd427ac3d26b55bab05c5ac6f0b1a9d9. Go ahead and pull master and it should be fixed up now.
